version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: ${DOCKERHUB_USERNAME:-local}/opencanvas-server:latest
    env_file: .env
    ports:
      - "5057:5057"
    networks: [stack]

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: ${DOCKERHUB_USERNAME:-local}/opencanvas-client:latest
    ports:
      - "8080:80"
    networks: [stack]

networks:
  stack:
    driver: bridge
