name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/opencanvas-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/opencanvas--client:${{ github.sha }}

      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/opencanvas-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/opencanvas--client:${{ github.sha }}
